# Generated by Django 5.1.6 on 2025-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titla', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
